apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkopay-test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: jkopay-test-pod
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: fir-service-paymentmessage-pod
    spec:
      containers:
        - name: jkopay-test
          image: registry.hub.docker.com/chen19980/jkopay:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080

